// This file is auto-generated by source/generate-mocks.js
// Do not edit manually. Run 'npm run generate:mocks' to regenerate.
//
// Mock for: @universityofmaryland/web-builder-library
// Description: Element builder utilities with fluent API

module.exports = {
    ElementBuilder: jest.fn().mockImplementation(function(...args) {
        return { __mockClass: 'ElementBuilder', args };
      }),
    StyleManager: jest.fn().mockImplementation(function(...args) {
        return { __mockClass: 'StyleManager', args };
      }),
    createStyleTag: jest.fn(),
    injectStyles: jest.fn(),
    LifecycleManager: jest.fn().mockImplementation(function(...args) {
        return { __mockClass: 'LifecycleManager', args };
      }),
    cleanupAll: jest.fn(),
    getGlobalLifecycleRegistry: jest.fn(),
    getLifecycleStats: jest.fn(),
    isElementBuilder: jest.fn(),
    isElementStyles: jest.fn(),
    isStyleDefinition: jest.fn()
  };
