// This file is auto-generated by source/generate-mocks.js
// Do not edit manually. Run 'npm run generate:mocks' to regenerate.
//
// Mock for: @universityofmaryland/web-token-library
// Description: Design tokens (colors, spacing, fonts, media queries)

module.exports = {
    color: {
    red: '#E21833',
    blue: '#2F7EDA',
    green: '#008000',
    gold: '#FFD200',
    white: '#FFFFFF',
    black: '#000000',
    redDark: '#A90007',
    gray: {
    darker: '#242424',
    dark: '#454545',
    mediumAA: '#757575',
    medium: '#7F7F7F',
    light: '#E6E6E6',
    lighter: '#F1F1F1',
    lightest: '#FAFAFA'
  }
  },
    spacing: {
    min: '8px',
    xs: '12px',
    sm: '16px',
    md: '24px',
    lg: '32px',
    xl: '40px',
    "2xl": '48px',
    "3xl": '56px',
    "4xl": '64px',
    "5xl": '72px',
    "6xl": '80px',
    "7xl": '96px',
    "8xl": '104px',
    max: '120px',
    maxWidth: {
    max: '1600px',
    larger: '1600px',
    large: '1400px',
    normal: '1280px',
    small: '992px',
    smallest: '800px'
  }
  },
    media: {
    breakpointValues: {
    small: {
    min: 320,
    max: 479
  },
    medium: {
    min: 480,
    max: 649
  },
    large: {
    min: 650,
    max: 767
  },
    tablet: {
    min: 768,
    max: 1023
  },
    desktop: {
    min: 1024,
    max: 1199
  },
    highDef: {
    min: 1200,
    max: 1499
  },
    maximum: {
    min: 1500
  }
  },
    breakpoints: {
    small: {
    min: '320px',
    max: '479px'
  },
    medium: {
    min: '480px',
    max: '649px'
  },
    large: {
    min: '650px',
    max: '767px'
  },
    tablet: {
    min: '768px',
    max: '1023px'
  },
    desktop: {
    min: '1024px',
    max: '1199px'
  },
    highDef: {
    min: '1200px',
    max: '1499px'
  },
    maximum: {
    min: '1500px'
  }
  },
    conditionals: {
    "--isMediaSmall": false,
    "--isMediaSmallMax": false,
    "--isMediaMedium": false,
    "--isMediaMediumMax": false,
    "--isMediaLarge": false,
    "--isMediaLargeMax": false,
    "--isMediaTablet": false,
    "--isMediaTabletMax": false,
    "--isMediaDesktop": false,
    "--isMediaDesktopMax": false,
    "--isMediaHighDef": false,
    "@media (min-width: 320px)": {
    "--isBreakpointSmall": true
  },
    "@media (max-width: 479px)": {
    "--isBreakpointSmallMax": true
  },
    "@media (min-width: 480px)": {
    "--isBreakpointMedium": true
  },
    "@media (max-width: 649px)": {
    "--isBreakpointMediumMax": true
  },
    "@media (min-width: 650px)": {
    "--isBreakpointLarge": true
  },
    "@media (max-width: 767px)": {
    "--isBreakpointLargeMax": true
  },
    "@media (min-width: 768px)": {
    "--isTablet": true
  },
    "@media (max-width: 1023px)": {
    "--isTabletMax": true
  },
    "@media (min-width: 1024px)": {
    "--isDesktop": true
  },
    "@media (max-width: 1199px)": {
    "--isDesktopMax": true
  },
    "@media (min-width: 1200px)": {
    "--isHighDef": true
  }
  },
    queries: {
    small: {
    min: 'min-width: 320px',
    max: 'max-width: 479px'
  },
    medium: {
    min: 'min-width: 480px',
    max: 'max-width: 649px'
  },
    large: {
    min: 'min-width: 650px',
    max: 'max-width: 767px'
  },
    tablet: {
    min: 'min-width: 768px',
    max: 'max-width: 1023px'
  },
    desktop: {
    min: 'min-width: 1024px',
    max: 'max-width: 1199px'
  },
    highDef: {
    min: 'min-width: 1200px',
    max: 'max-width: 1499px'
  },
    maximum: {
    min: 'min-width: 1500px'
  }
  }
  },
    font: {
    family: {
    campaign: "'Barlow Condensed', Arial Narrow, sans-serif",
    sans: "'Interstate', Helvetica, Arial, Verdana, sans-serif",
    serif: "'Crimson Pro', Georgia, serif",
    mono: 'monospace'
  },
    size: {
    min: '12px',
    sm: '14px',
    base: '16px',
    lg: '18px',
    xl: '20px',
    "2xl": '22px',
    "3xl": '24px',
    "4xl": '32px',
    "5xl": '44px',
    "6xl": '56px',
    "7xl": '64px',
    "8xl": '72px',
    "9xl": '80px',
    "10xl": '96px',
    max: '120px'
  },
    weight: {
    thin: '100',
    extraLight: '200',
    light: '300',
    normal: '400',
    medium: '500',
    semiBold: '600',
    bold: '700',
    extraBold: '800',
    black: '900',
    extraBlack: '950'
  }
  }
  };
