// This file is auto-generated by source/generate-mocks.js
// Do not edit manually. Run 'npm run generate:mocks' to regenerate.
//
// Mock for: @universityofmaryland/web-utilities-library
// Description: Shared utility functions for DOM, styles, and validation

module.exports = {"FCP_THRESHOLD_GOOD":1.8,"FCP_THRESHOLD_NEEDS_IMPROVEMENT":3,"LCP_THRESHOLD_GOOD":2.5,"LCP_THRESHOLD_NEEDS_IMPROVEMENT":4,"THRESHOLDS":{"lcp":{"good":2.5,"needsImprovement":4,"poor":4},"fcp":{"good":1.8,"needsImprovement":3,"poor":3}},"VERSION":"0.1.0","theme":{}};
