// Mock for @universityofmaryland/web-token-library/media
module.exports = {
  breakpointValues: {
    small: { min: 320, max: 479 },
    medium: { min: 480, max: 649 },
    large: { min: 650, max: 767 },
    tablet: { min: 768, max: 1023 },
    desktop: { min: 1024, max: 1199 },
    highDef: { min: 1200, max: 1499 },
    maximum: { min: 1500 },
  },
  breakpoints: {
    small: { min: '320px', max: '479px' },
    medium: { min: '480px', max: '649px' },
    large: { min: '650px', max: '767px' },
    tablet: { min: '768px', max: '1023px' },
    desktop: { min: '1024px', max: '1199px' },
    highDef: { min: '1200px', max: '1499px' },
    maximum: { min: '1500px' },
  },
  conditionals: {
    '--isMediaSmall': false,
    '--isMediaSmallMax': false,
    '--isMediaMedium': false,
    '--isMediaMediumMax': false,
    '--isMediaLarge': false,
    '--isMediaLargeMax': false,
    '--isMediaTablet': false,
    '--isMediaTabletMax': false,
    '--isMediaDesktop': false,
    '--isMediaDesktopMax': false,
    '--isMediaHighDef': false,
    '@media (min-width: 320px)': { '--isBreakpointSmall': true },
    '@media (max-width: 479px)': { '--isBreakpointSmallMax': true },
    '@media (min-width: 480px)': { '--isBreakpointMedium': true },
    '@media (max-width: 649px)': { '--isBreakpointMediumMax': true },
    '@media (min-width: 650px)': { '--isBreakpointLarge': true },
    '@media (max-width: 767px)': { '--isBreakpointLargeMax': true },
    '@media (min-width: 768px)': { '--isTablet': true },
    '@media (max-width: 1023px)': { '--isTabletMax': true },
    '@media (min-width: 1024px)': { '--isDesktop': true },
    '@media (max-width: 1199px)': { '--isDesktopMax': true },
    '@media (min-width: 1200px)': { '--isHighDef': true },
  },
  queries: {
    small: { min: 'min-width: 320px', max: 'max-width: 479px' },
    medium: { min: 'min-width: 480px', max: 'max-width: 649px' },
    large: { min: 'min-width: 650px', max: 'max-width: 767px' },
    tablet: { min: 'min-width: 768px', max: 'max-width: 1023px' },
    desktop: { min: 'min-width: 1024px', max: 'max-width: 1199px' },
    highDef: { min: 'min-width: 1200px', max: 'max-width: 1499px' },
    maximum: { min: 'min-width: 1500px' },
  },
};
