export const BREAKPOINTS = {
  LARGE: 1200,
  MEDIUM: 800,
  SMALL: 600,
};
export const ELEMENTS = {
  PATHWAY_CONTAINER: 'umd-pathway-container',
};
export const SLOTS = {
  IMAGE: 'image',
  HEADLINE: 'headline',
  EYEBROW: 'eyebrow',
  TEXT: 'text',
  ACTIONS: 'actions',
  HIGHLIGHT: 'highlight',
  HIGHLIGHT_ATTRIBUTION: 'highlight-attribution',
};
export const VARIABLES = {
  ELEMENT_NAME: 'umd-element-pathway',
  ATTRIBUTE_HIGHLIGHT: 'data-highlight',
  ATTRIBUTE_IMAGE_POSITION: 'data-image-position',
  ATTRIBUTE_IMAGE_SCALED: 'data-image-scaled',
  ATTRIBUTE_THEME: 'data-theme',
  ATTRIBUTE_HERO: 'data-hero',
  THEME_LIGHT: 'light',
  THEME_DARK: 'dark',
  THEME_MARYLAND: 'maryland',
  THEME_WHITE: 'white',
};

export const REFERENCES = {
  IS_WITH_IMAGE: `[${VARIABLES.ATTRIBUTE_IMAGE_POSITION}]`,
  IS_WITH_IMAGE_RIGHT: `[${VARIABLES.ATTRIBUTE_IMAGE_POSITION}="right"]`,
  IS_WITH_IMAGE_LEFT: `[${VARIABLES.ATTRIBUTE_IMAGE_POSITION}="left"]`,
  IS_WITH_IMAGE_SCALED: `[${VARIABLES.ATTRIBUTE_IMAGE_SCALED}="true"]`,
  IS_WITHOUT_IMAGE_SCALED: `[${VARIABLES.ATTRIBUTE_IMAGE_SCALED}="false"]`,
  IS_WITH_HIGHLIGHT: `[${VARIABLES.ATTRIBUTE_HIGHLIGHT}]`,
  IS_THEME_DARK: `[${VARIABLES.ATTRIBUTE_THEME}='${VARIABLES.THEME_DARK}']`,
  IS_THEME_LIGHT: `[${VARIABLES.ATTRIBUTE_THEME}='${VARIABLES.THEME_LIGHT}']`,
  IS_THEME_MARYLAND: `[${VARIABLES.ATTRIBUTE_THEME}='${VARIABLES.THEME_MARYLAND}']`,
  IS_THEME_WHITE: `[${VARIABLES.ATTRIBUTE_THEME}='${VARIABLES.THEME_WHITE}']`,
  IS_WITH_HERO: `[${VARIABLES.ATTRIBUTE_HERO}]`,
};
