export const BREAKPOINTS = {
  tablet: 768,
  desktop: 1024,
};
export const ELEMENTS = {
  HERO_CONTAINER: `umd-hero-container`,
  HERO_BODY: 'umd-hero-body',
  HERO_BODY_WRAPPER: 'umd-hero-body-wrapper',
};
export const SLOTS = {
  IMAGE: 'image',
  HEADLINE: 'headline',
  EYEBROW: 'eyebrow',
  TEXT: 'text',
  ACTIONS: 'actions',
};
export const VARIABLES = {
  TYPE_DEFAULT: 'default',
  TYPE_DEFAULT_CENTERED: 'default-centered',
  TYPE_STACKED: 'stacked',
  TYPE_STACKED_INTERIOR: 'stacked-interior',
  TYPE_MINIMAL: 'minimal',
  TYPE_OVERLAY: 'overlay',
  TYPE_LOGO: 'logo',
  THEME_LIGHT: 'light',
  THEME_DARK: 'dark',
  THEME_MARYLAND: 'maryland',
  THEME_WHITE: 'white',
  TEXT_ALIGN_LEFT: 'left',
  TEXT_ALIGN_CENTER: 'center',
  ATTRIBUTE_THEME: 'theme',
  ATTRIBUTE_TYPE: 'type',
  ATTRIBUTE_TEXT_ALIGN: 'text-align',
  ATTRIBUTE_HAS_IMAGE: 'has-image',
  ATTRIBUTE_WITHIN_LOCK: 'within-lock',
};
export const NAMING = {
  DEFAULT_ATTR: `[${VARIABLES.ATTRIBUTE_TYPE}='${VARIABLES.TYPE_DEFAULT}']`,
  STACKED_ATTR: `[${VARIABLES.ATTRIBUTE_TYPE}='${VARIABLES.TYPE_STACKED}']`,
  OVERLAY_ATTR: `[${VARIABLES.ATTRIBUTE_TYPE}='${VARIABLES.TYPE_OVERLAY}']`,
  MINIMAL_ATTR: `[${VARIABLES.ATTRIBUTE_TYPE}='${VARIABLES.TYPE_MINIMAL}']`,
  LOGO_ATTR: `[${VARIABLES.ATTRIBUTE_TYPE}='${VARIABLES.TYPE_LOGO}']`,
  DARK_ATTR: `[${VARIABLES.ATTRIBUTE_THEME}='${VARIABLES.THEME_DARK}']`,
  LIGHT_ATTR: `[${VARIABLES.ATTRIBUTE_THEME}='${VARIABLES.THEME_LIGHT}']`,
  MD_ATTR: `[${VARIABLES.ATTRIBUTE_THEME}='${VARIABLES.THEME_MARYLAND}']`,
  WHITE_ATTR: `[${VARIABLES.ATTRIBUTE_THEME}='${VARIABLES.THEME_WHITE}']`,
  TEXT_ALIGN_CENTER: `[${VARIABLES.ATTRIBUTE_TEXT_ALIGN}='${VARIABLES.TEXT_ALIGN_CENTER}']`,
  HAS_IMAGE: `[${VARIABLES.ATTRIBUTE_HAS_IMAGE}]`,
  IS_WITHIN_LOCK: `[${VARIABLES.ATTRIBUTE_WITHIN_LOCK}]`,
};
