export const BREAKPOINTS = {
  medium: 768,
};
export const ELEMENTS = {
  HERO_CONTAINER: `umd-hero-container`,
  HERO_BODY: 'umd-hero-body',
  HERO_BODY_WRAPPER: 'umd-hero-body-wrapper',
};
export const SLOTS = {
  IMAGE: 'image',
  HEADLINE: 'headline',
  EYEBROW: 'eyebrow',
  TEXT: 'text',
  ACTIONS: 'actions',
};
export const VARIABLES = {
  TYPE_DEFAULT: 'default',
  TYPE_STACKED: 'stacked',
  TYPE_MINIMAL: 'minimal',
  TYPE_OVERLAY: 'overlay',
  THEME_LIGHT: 'light',
  THEME_DARK: 'dark',
  THEME_MARYLAND: 'maryland',
  ATTRIBUTE_THEME: 'theme',
  ATTRIBUTE_TYPE: 'type',
};
export const NAMING = {
  DEFAULT_ATTR: `[${VARIABLES.ATTRIBUTE_TYPE}='${VARIABLES.TYPE_DEFAULT}']`,
  STACKED_ATTR: `[${VARIABLES.ATTRIBUTE_TYPE}='${VARIABLES.TYPE_STACKED}']`,
  OVERLAY_ATTR: `[${VARIABLES.ATTRIBUTE_TYPE}='${VARIABLES.TYPE_OVERLAY}']`,
  MINIMAL_ATTR: `[${VARIABLES.ATTRIBUTE_TYPE}='${VARIABLES.TYPE_MINIMAL}']`,
  DARK_ATTR: `[${VARIABLES.ATTRIBUTE_THEME}='${VARIABLES.THEME_DARK}']`,
  LIGHT_ATTR: `[${VARIABLES.ATTRIBUTE_THEME}='${VARIABLES.THEME_LIGHT}']`,
  MD_ATTR: `[${VARIABLES.ATTRIBUTE_THEME}='${VARIABLES.THEME_MARYLAND}']`,
};
